services:
  web:
    build: .
    ports:
      - "81:80"
    volumes:
      - ./crud:/var/www/html
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 300M
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: C@!232104
      MYSQL_DATABASE: mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/database.sql:/docker-entrypoint-initdb.d/database.sql
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mydba
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 200M

volumes:
  db_data:
